#4on4 : 2024 Power Ranking
---------------------------

## Dependencies

In [13]:
import json
import pandas as pd
import plotly.express as px

## Functions

In [14]:
def plot_bar(dataframe: pd.DataFrame, x: str, y: str, title: str, x_label: str, y_label: str):
    """Compute a Bar Chart using Plotly express
    :param dataframe: dataframe as input (has to be sorted)
    :param x: x value for bar chart (labels)
    :param y: y value for bar chart (feature)
    :param title: title of the chart
    :param x_label: x-axis label
    :param y_label: y-axis label
    :return: bar chart as plotly "Figure" object.
    """
    if x_label is None:
        x_label = x

    if y_label is None:
        y_label = y

    fig = px.bar(data_frame=dataframe.head(10), y=y, x=x,
                 labels={x: x_label, y: y_label},
                 title=title, color=y,
                 width=960, height=540, color_continuous_scale='orrd')

    fig.update_layout(xaxis={'categoryorder': 'total descending'})
    fig.update_coloraxes(showscale=False)
    return fig

## Data Loading & Pre-treatments

In [15]:
with open('../data/selection_2024.json', 'r', encoding='utf-8') as j_file:
    json_data = json.load(j_file)

data = pd.DataFrame(json_data)
data

,artist_list,data,genre,label,request,title
0,"[blasterjaxx, hardwell, maddix]","{'s_id': 'qmr6e0bx', 's_title': '16'}",[hard techno],[revealed],"blasterjaxx, hardwell, maddix 16",16
1,"[ekko & sidetrack, mk]","{'s_id': 'cxsruom1', 's_title': '17 (Ekko & Si...",[drum & bass],[[no labels]],mk 17 ekko & sidetrack bootleg,17 ekko & sidetrack bootleg
2,"[cimone, deadline, duskee, emily makis, fricti...","{'s_id': '', 's_title': ''}",[drum & bass],[shogun audio],"cimone, deadline, duskee, emily makis, frictio...",never let you down
3,"[lexed, oshan]","{'s_id': '4owlyi76', 's_title': '4 AM'}",[future house / future bounce],[future house cloud],"lexed, oshan 4 am",4 am
4,"[bad computer, ryan coss]","{'s_id': 'a3ok10ce', 's_title': '4D'}",[electro house],[monstercat],"bad computer, ryan coss 4d",4d
...,...,...,...,...,...,...
300,[diamond eyes],"{'s_id': '6f24dq03', 's_title': 'Worship'}",[drum & bass],[ncs],diamond eyes worship,worship
301,"[ayah marar, murdock]","{'s_id': 'tuxsb1on', 's_title': 'Lost In You'}",[drum & bass],[rampage],"ayah marar, murdock lost in you",lost in you
302,[hardwell],"{'s_id': 'pvqdi5wy', 's_title': 'XTC'}",[hard techno],[revealed],hardwell xtc,xtc
303,"[ariana grande, ellis]","{'s_id': '', 's_title': ''}",[future house / future bounce],[[no labels]],ariana grande yes and ellis remix,yes and ellis remix
304,"[don diablo, sandro cavazza]","{'s_id': '9dgc7xwy', 's_title': 'Young Again'}",[future house / future bounce],[hexagon],"don diablo, sandro cavazza young again",young again

In [16]:
# Stats by artist
data_art = data.explode('artist_list').reset_index(drop=True)
data_art.rename({'artist_list': 'artist'}, axis=1, inplace=True)

In [17]:
# Stats by labels
data_lab = data.explode('label').reset_index(drop=True)
data_lab = data_lab.loc[data_lab.label != '[no labels]']

In [18]:
# Stats by genre
data_gen = data.explode('genre').reset_index(drop=True)

## Basic statistics

### Artists of the year by number of release

In [19]:
data_art_count = (data_art[['artist', 'title']]
                  .groupby('artist', as_index=False)
                  .count()
                  .rename({'title': 'n_release'}, axis=1)
                  .sort_values('n_release', ascending=False)
                  .reset_index(drop=True))

data_art_count.describe()

        n_release
count  433.000000
mean     1.334873
std      0.931003
min      1.000000
25%      1.000000
50%      1.000000
75%      1.000000
max      8.000000

In [20]:
bar_artists_release = plot_bar(data_art_count.head(10), 'artist', 'n_release',
                               'Number of release by Artist (Top 10)<br><sup>Remixes included</sup>',
                               'Artists', 'Number of releases')

bar_artists_release.show()


### Labels of the year by number of release

In [21]:
data_lab_count = (data_lab[['label', 'title']]
                  .groupby('label', as_index=False)
                  .count()
                  .rename({'title': 'n_release'}, axis=1)
                  .sort_values('n_release', ascending=False)
                  .reset_index(drop=True))

data_lab_count.describe()

       n_release
count  91.000000
mean    3.219780
std     6.762317
min     1.000000
25%     1.000000
50%     1.000000
75%     2.000000
max    54.000000

In [22]:
bar_label_release = plot_bar(data_lab_count.head(10), 'label', 'n_release', 'Number of release by Label (Top 10)',
                             'Labels', 'Number of releases')
bar_label_release.show()

### Genre of the year by number of release

In [23]:
data_gen_count = (data_gen[['genre', 'title']]
                  .groupby('genre', as_index=False)
                  .count()
                  .rename({'title': 'n_release'}, axis=1)
                  .sort_values('n_release', ascending=False)
                  .reset_index(drop=True))

data_gen_count.describe()

        n_release
count   40.000000
mean     7.875000
std     18.173223
min      1.000000
25%      2.000000
50%      2.500000
75%      5.250000
max    112.000000

In [24]:
bar_genre_release = plot_bar(data_gen_count.head(10), 'genre', 'n_release', 'Number of release by Genre (Top 10)',
                             'Music Genres', 'Number of releases')
bar_genre_release.show()